### ISSUE TITLE
API key should never publish online

### ISSUE THREAD

**Issue by siutsin** [gautamkrishnar/naughtychecker.js#5]
Instead, set the env variable in travis

- [ ] Regenerate token as it is exposed
- [ ] Set token as environment variable in travis

**Comment by gautamkrishnar** [comment]
@siutsin yes its already encrypted using travis command line interface 👍 https://docs.travis-ci.com/user/deployment/npm/

**Comment by siutsin** [comment]
Got it, thought that was the original key 👍
